-- 코드를 작성해주세요
WITH PARENT AS (
    SELECT DISTINCT(PARENT_ITEM_ID) FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)

SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
Where ITEM_ID not in (SELECT PARENT_ITEM_ID FROM PARENT)
order by ITEM_ID DESC