-- 코드를 입력하세요
WITH SUM_SALES AS (SELECT *,sum(sales) as sum_sales FROM BOOK_SALES
WHERE sales_date BETWEEN '2022-01-01' and '2022-01-31'
GROUP BY BOOK_ID),


BOOKS AS (SELECT B.BOOK_ID,A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID)

SELECT B.AUTHOR_ID, B.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SUM_SALES) AS TOTAL_SALES FROM BOOKS B
JOIN SUM_SALES S ON B.BOOK_ID = S.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
order by B.AUTHOR_ID asc , B.CATEGORY DESC





