-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_Id,F.FILE_NAME,F.FILE_EXT) 
        AS FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
where B.views = (SELECT max(views) from USED_GOODS_BOARD)
order by F.FILE_ID DESC
# SELECT * FROM USED_GOODS_BOARD